In [18]:
#!pip install selenium

In [19]:
from selenium import webdriver   # type: ignore
from selenium.webdriver.edge.service import Service # type: ignore
from selenium.webdriver.common.by import By  # type: ignore

import pandas as pd  # type: ignore

In [20]:
edge_service = Service(executable_path="C:/Users/HP/Downloads/edgedriver_win64/msedgedriver.exe")  # Update with your path        
driver = webdriver.Edge(service=edge_service) 
url = 'https://www.jiji.ng/vehicles'  # URL of the website you want to open     
driver.get(url)  # Open a website

In [21]:
driver

In [22]:
item_col = driver.find_element(By.CLASS_NAME, 'masonry-column')
item = item_col.find_element(By.CLASS_NAME, 'masonry-item')
product_name = item.find_element(By.CLASS_NAME, 'qa-advert-title').text
product_price = item.find_element(By.CLASS_NAME, 'qa-advert-price').text
product_description = item.find_element(By.CLASS_NAME, 'b-list-advert-base__description-text').text
#product_location = item.find_element(By.CLASS_NAME, 'b-list-advert_region_text').text
product_grade = item.find_element(By.CLASS_NAME, 'b-list-advert-base__item-attr').text
product_img = item.find_element(By.TAG_NAME,'img')

product_grade

'Brand New'

In [23]:
item_col = driver.find_element(By.CLASS_NAME, 'masonry-column')

for item in item_col.find_elements(By.CLASS_NAME, 'masonry-item'):
    item = item_col.find_element(By.CLASS_NAME, 'masonry-item')
    
    for goods in item:
        product_name = goods.find_element(By.CLASS_NAME, 'qa-advert-title')
        Name = product_name.text.strip() if product_name else 'N/A'
        
        product_price = goods.find_elements(By.CLASS_NAME, 'qa-advert-price')
        price = product_price.text.strip() if product_price else 'N/A'
        
        product_description = goods.find_element(By.CLASS_NAME, 'b-list-advert-base__description-text')
        description = product_description.text.strip() if product_description else 'N/A'    
        
        
        try:
        product_grade = prproduct_grade = item.find_element(By.CLASS_NAME, 'b-list-advert-base__item-attr')
        grade = product_grade.text.strip() if product_grade else 'N/A'
        
        except:
            grade = 'N/A'   
            
        product = {
            'Name':Name,
            'Price':price,
            'Description':description,
            'Grade':grade   
            
        }

IndentationError: expected an indented block after 'try' statement on line 17 (4202533762.py, line 18)

In [26]:
edge_service = Service(executable_path="C:/Users/HP/Downloads/edgedriver_win64/msedgedriver.exe")  # Update with your path        
driver = webdriver.Edge(service=edge_service) 
url = 'https://www.jiji.ng/vehicles'  # URL of the website you want to open     
driver.get(url)  # Open a website  

jiji_data = []

item_col = driver.find_elements(By.CLASS_NAME, 'masonry-column')

for item in item_col:
    goods = item.find_elements(By.CLASS_NAME, 'masonry-item')
    for good in goods:
        product_name = good.find_element(By.CLASS_NAME, 'qa-advert-title')
        name = product_name.text.strip() if product_name else 'NA'

        product_price = good.find_element(By.CLASS_NAME, 'qa-advert-price')
        price = product_price.text.strip() if product_price else 'NA'
        
        product_description = good.find_element(By.CLASS_NAME, 'b-list-advert-base__description-text')
        description = product_description.text.strip() if product_description else 'NA'
        
        #product_location = good.find_element(By.CLASS_NAME, 'b-list-advert_region_text')
        #location = product_location.text.strip() if product_location else 'NA'
        
        product_img = good.find_element(By.TAG_NAME,'img')
        image = product_img.get_attribute('src') if product_img else 'NA'

        try:
            product_grade = good.find_element(By.CLASS_NAME, 'b-list-advert-base__item-attr')
            grade = product_grade.text.strip() if product_grade else 'NA'
        except:
            grade = 'NA'

        product = {
            'Name': name,
            'Price': price,
            'Description': description,
            'Image_Link': image,
            #'Location': location,
            'Grade': grade
        }
        jiji_data.append(product)
driver.quit() 
#always quit the driver

In [40]:
jiji_data

[{'Name': 'Amasco Engine Oil 1litres',
  'Price': '₦ 4,750',
  'Description': 'Amasco engine oil 1litres',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/165386540_MzAwLTM5OC0yMmJkN2RhMmEyLTE.webp',
  'Grade': 'Brand New'},
 {'Name': 'Hyundai Accent GLS Automatic 2012 Black',
  'Price': '₦ 4,950,000',
  'Description': "It's ok, buy and drive, faulty ac evaporator",
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/178194801_MzAwLTE2OS0zN2Y0MjhlZmM5.webp',
  'Grade': 'Local Used'},
 {'Name': 'Complete Honda Engine And Gearbox Available.',
  'Price': '₦ 250,000',
  'Description': 'We sell direct tokumbo all kind of Honda Engine and Gearbox',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/98436511_MzAwLTMwMC1hNDE3MzZjY2Uw.webp',
  'Grade': 'Used'},
 {'Name': 'Shock Absorber Pad for All Motor',
  'Price': '₦ 30,000',
  'Description': 'Original shock absorber pad made from good Thailand quality (high standard)',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/30499868_20190607-121243_300x300.jpg',
  'Grade': 'Brand New'},
 {'Name': 'Original Bushing For All Cars',
  'Price': '₦ 4,000',
  'Description': 'Original bushing for your lower arm and your stabilizer linkage rubber. The best you can trust for...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/35821478_20191014-165128_300x169.jpg',
  'Grade': 'Brand New'},
 {'Name': 'Hyundai Sonata Top Cyclinder Valve Cover 08/09 Model',
  'Price': '₦ 69,999',
  'Description': 'Direct toks first grade japanese untouched engines top cyclinder valve cover for sonata neatly used...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/164321258_MzAwLTQwMC0yMTZmNDQ0YjI4.webp',
  'Grade': 'Used'},
 {'Name': 'O2 Sensor Adapter',
  'Price': '₦ 15,000',
  'Description': 'Removing of check engine light',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/131511849_MzAwLTUzNC0yMzc2Y2MyOGFjLTE.webp',
  'Grade': 'Used'},
 {'Name': 'HONDA Brain Box and ABS',
  'Price': '₦ 35,000',
  'Description': 'I Sale All Types of Honda Brain Box, ABS, Norzel, Gearbox Sensor, ETC With Friendly Price, Also...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/128069763_MzAwLTQwMC1iYjZlZDhkMGVl.webp',
  'Grade': 'Used'},
 {'Name': 'Mercedes-Benz E63 2017 Black',
  'Price': '₦ 65,000,000',
  'Description': 'Foreign used mercedes benz e63 2017 model with original custom duty location abuja call or dm for...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/176013176_MzAwLTQwMC0yNTNmZWZjMWJm.webp',
  'Grade': 'Foreign Used'},
 {'Name': 'Oando Atf Dexron LLL',
  'Price': '₦ 25,000',
  'Description': 'Oando ATF dexron lll',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/173896776_MzAwLTUzMy01YjI3MmIxYTEyLTE.webp',
  'Grade': 'Bulk prices'},
 {'Name': "Honda Engine's and Acura Engines (Complete and First Grades)",
  'Price': '₦ 109,609',
  'Description': '(Honda & Acura Expert) . We specialize in any year models type of your honda & acura: complete...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/11492161_1504917149327_1_300x225.webp',
  'Grade': 'NA'},
 {'Name': 'Toyota/Lexus Automatic Transmission Valve Body 22pin V6',
  'Price': '₦ 500,000',
  'Description': 'Direct toks first grade japanese untouched automatic transmission valve body 22pin v6 wit maximum...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/148323411_MzAwLTQwMC03ZWQxMTcwMmQ1.webp',
  'Grade': 'Used'},
 {'Name': 'Convertion of Key to Keyless of Any Vehicle.',
  'Price': '₦ 200,000',
  'Description': 'You can convert your car from key to keyless. The price is depending on the car you want to convert.',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/97479395_MzAwLTM4OC01MzczZGZiMDBkLTE.webp',
  'Grade': 'Brand New'},
 {'Name': 'Armrest Lexus Es350',
  'Price': '₦ 150,000',
  'Description': 'We have all kinds of armrest you want just give us a call.',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/129266773_MzAwLTQwMS02YTZlYzA1MzVm.webp',
  'Grade': 'Used'},
 {'Name': 'JB Weld Industrial Weld',
  'Price': '₦ 33,000',
  'Description': 'High quality Industrial JB weld',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/128956105_MzAwLTM5OS1mYTNlMTg3YmNmLTE.webp',
  'Grade': 'Bulk prices'},
 {'Name': 'Toyota/Lexus Gears Fiber 22pin V6',
  'Price': '₦ 400,000',
  'Description': 'Direct toks automatic transmission fiber 22pin first grade japanese untouched wit maximum warranty...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/141489977_MzAwLTQwMC05YzFlODUyZjE4.webp',
  'Grade': 'Used'},
 {'Name': 'Gx470 Converted to Prado 2020 Model',
  'Price': '₦ 1,600,000',
  'Description': 'Rim. Tyar. Front and back light',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/168986433_MzAwLTQwMC0wODAyYjA2MTc3.webp',
  'Grade': 'Brand New'},
 {'Name': 'Suzuki Every Engine',
  'Price': '₦ 500,000',
  'Description': 'Direct Japan Belgium 500000 out gearbox Best grades',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/154757453_MzAwLTUzMi1hN2M1MmE2ZTY2.webp',
  'Grade': 'Used'},
 {'Name': 'Toyota Camry 2010 Gray',
  'Price': '₦ 8,000,000',
  'Description': 'This Toyota Camry 2010 is a locally used car. It’s Accident free, perfect engine condition, complete...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/175291269_MzAwLTIyNS0xZTFlNWM3MWU5.webp',
  'Grade': 'Local Used'},
 {'Name': 'Corolla Engine Sitting (Japan Standard)',
  'Price': '₦ 18,000',
  'Description': 'Original engine seating for corolla 2003-2005 . Japan standard',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/42436444_20200309-104855_300x225.jpg',
  'Grade': 'Brand New'},
 {'Name': 'Yahoo Exhaust Pot',
  'Price': '₦ 80,000',
  'Description': 'Enhancement of loud sound',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/164416485_MzAwLTUzMy1iNTUyN2ZiZDk3.webp',
  'Grade': 'Used'},
 {'Name': 'Ac Vent 2007/2010 Camry',
  'Price': '₦ 60,000',
  'Description': 'We have all kinds of Ac vent you want to buy.',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/157474686_MzAwLTUwMS0zNDU1NmU4ZmNl.webp',
  'Grade': 'Used'},
 {'Name': 'We Deal With All Types of Honda New Hub Bearing',
  'Price': '₦ 20,000',
  'Description': 'We supply all types of New Honda hub bearings with Affordable Price , eg, Honda Accord, Honda CR-V,...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/173019924_MzAwLTQzMi05YmJkNTE5YmYy.webp',
  'Grade': 'Brand New'},
 {'Name': 'Inner Transmission Solenoid Valve ABCD Gear Shifters',
  'Price': '₦ 45,000',
  'Description': 'Direct follow comes inner transmission solenoid valve abcd gear shifters for honda and acura...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/150877391_MzAwLTQwMC0zZGM0YWU3MDFl.webp',
  'Grade': 'Used'}]

In [28]:
df = pd.DataFrame(jiji_data)
df.head()

,Name,Price,Description,Image_Link,Grade
0,Amasco Engine Oil 1litres,"₦ 4,750",Amasco engine oil 1litres,https://pictures-nigeria.jijistatic.net/165386...,Brand New
1,Hyundai Accent GLS Automatic 2012 Black,"₦ 4,950,000","It's ok, buy and drive, faulty ac evaporator",https://pictures-nigeria.jijistatic.net/178194...,Local Used
2,Complete Honda Engine And Gearbox Available.,"₦ 250,000",We sell direct tokumbo all kind of Honda Engin...,https://pictures-nigeria.jijistatic.net/984365...,Used
3,Shock Absorber Pad for All Motor,"₦ 30,000",Original shock absorber pad made from good Tha...,https://pictures-nigeria.jijistatic.net/304998...,Brand New
4,Original Bushing For All Cars,"₦ 4,000",Original bushing for your lower arm and your s...,https://pictures-nigeria.jijistatic.net/358214...,Brand New

In [29]:
df.dtypes

Name           object
Price          object
Description    object
Image_Link     object
Grade          object
dtype: object

In [36]:
df['SellingPrice'] = df['Price'].astype(str).replace(r'[^\d]', '', regex=True).astype(float)
df.head()

,Name,Price,Description,Image_Link,Grade,SellingPrice,SellingPric
0,Amasco Engine Oil 1litres,47500.0,Amasco engine oil 1litres,https://pictures-nigeria.jijistatic.net/165386...,Brand New,475000.0,475000.0
1,Hyundai Accent GLS Automatic 2012 Black,49500000.0,"It's ok, buy and drive, faulty ac evaporator",https://pictures-nigeria.jijistatic.net/178194...,Local Used,495000000.0,495000000.0
2,Complete Honda Engine And Gearbox Available.,2500000.0,We sell direct tokumbo all kind of Honda Engin...,https://pictures-nigeria.jijistatic.net/984365...,Used,25000000.0,25000000.0
3,Shock Absorber Pad for All Motor,300000.0,Original shock absorber pad made from good Tha...,https://pictures-nigeria.jijistatic.net/304998...,Brand New,3000000.0,3000000.0
4,Original Bushing For All Cars,40000.0,Original bushing for your lower arm and your s...,https://pictures-nigeria.jijistatic.net/358214...,Brand New,400000.0,400000.0

In [38]:
df['sellingprice'] = df['SellingPrice'] + (0.2 * df['SellingPrice'])
df.head(2)

,Name,Price,Description,Image_Link,Grade,SellingPrice,SellingPric,sellingprince,sellingprice
0,Amasco Engine Oil 1litres,47500.0,Amasco engine oil 1litres,https://pictures-nigeria.jijistatic.net/165386...,Brand New,475000.0,475000.0,570000.0,570000.0
1,Hyundai Accent GLS Automatic 2012 Black,49500000.0,"It's ok, buy and drive, faulty ac evaporator",https://pictures-nigeria.jijistatic.net/178194...,Local Used,495000000.0,495000000.0,594000000.0,594000000.0

In [39]:
df.to_excel('jiji_data.xlsx', index=False)